# -*- coding:utf-8 -*-
#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:slots
#

from __future__ import absolute_import
from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from demo.ttypes import *

